[package]
name = "kvs"
version = "0.1.0"
description = "a key-value server"
authors = ["Ruihang Xia <waynestxia@gmail.com>"]
edition = "2018"

[dependencies]
clap = { features = ["yaml"] }

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
